name: "runner-test"

on:
  pull_request:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  builder:
    runs-on: builder

    steps:
      - run: echo foo
